name: "Run tests"

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code of the repository"
        uses: actions/checkout@v4

      - name: "Setup the environment"
        run: pip install -r requirements.txt

      - name: "Run tests"
        run: pytest test -s -v
        